RAWSET_PATH = '/home/gtzan/data/gan_preprocessing/tfrecords'
RAWDATA_ROOT_PATH = '/home/gtzan/data'
MODEL_ROOT_PATH = '/home/gtzan/ssd/models'
EPOCHS = 20
DEFAULT_SAMPLING_RATE = 22050
DROPOUT_RATE = 0.5
BN_AXIS = 3
PAD_SIZE = ((0, 0), (1, 0))
STEPS = 2500
WAVS_TO_PREDICT_ROOT_PATH = RAWDATA_ROOT_PATH + '/gan_preprocessing/wav'
